"""Final Recommendation Report — Clean executive summary with Markdown and PDF export."""

import streamlit as st
from datetime import datetime, timezone
from urllib.parse import urlparse
from fpdf import FPDF

st.set_page_config(page_title="ProcureX — Final Report", layout="wide")

try:
    from app import apply_custom_css, init_session_state
    apply_custom_css()
    init_session_state()
except Exception:
    pass

def generate_pdf_report(requirement_text, top_supplier, alternatives, spent_usd) -> bytes:
    """Generate a clean executive PDF report using FPDF."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "ProcureX Procurement Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 6, f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)
    
    # Requirement
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "1. Requirement Prompt:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, requirement_text)
    pdf.ln(6)
    
    # Primary Recommendation
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "2. Primary Supplier Recommendation:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 11)
    
    top_name = top_supplier.name
    web_url = top_supplier.website or (top_supplier.source_urls[0] if top_supplier.source_urls else "N/A")
    pdf.cell(0, 6, f"Candidate: {top_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Website / Link: {web_url}", new_x="LMARGIN", new_y="NEXT")
    
    best_price = None
    min_moq = None
    if top_supplier.products:
        prices = [p.normalized_unit_price for p in top_supplier.products if p.normalized_unit_price]
        moqs = [p.moq for p in top_supplier.products if p.moq]
        best_price = min(prices) if prices else None
        min_moq = min(moqs) if moqs else None
        
    if best_price is not None:
        pdf.cell(0, 6, f"Unit Price: Rs. {best_price:.1f}/pc", new_x="LMARGIN", new_y="NEXT")
    if min_moq is not None:
        pdf.cell(0, 6, f"Minimum Order Quantity (MOQ): {min_moq:,} units", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    
    # Alternatives
    if alternatives:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "3. Candidate Alternatives:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for i, (alt, _) in enumerate(alternatives, start=2):
            alt_url = alt.website or (alt.source_urls[0] if alt.source_urls else "N/A")
            pdf.cell(0, 6, f"#{i} {alt.name} - Link: {alt_url}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(6)
        
    # Audit summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "4. Research Audit Summary:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Micro-Query Cost Spent: ${spent_usd:.3f} USD", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Generated by ProcureX Autonomous B2B Procurement Intelligence Agent - An APEX Creation", new_x="LMARGIN", new_y="NEXT", align="C")
    
    return bytes(pdf.output())

st.markdown("<h1>Final Recommendation <span class='gradient-text'>Report</span></h1>", unsafe_allow_html=True)
st.markdown("*Evidence-backed procurement recommendation with complete audit transparency.*")

session = st.session_state.get("research_session")

if not session or not getattr(session, "scores", None) or not session.scores:
    st.markdown("""
    <div class="glass-card" style="text-align:center; padding:3rem;">
        <h3>Report Not Ready</h3>
        <p style="color:#94a3b8;">Complete a full research session to generate the procurement recommendation report.</p>
        <p style="color:#64748b;">Navigate to <strong>Requirement Input</strong> to begin.</p>
    </div>
    """, unsafe_allow_html=True)
    st.stop()

ranked = session.get_ranked_suppliers()

if not ranked:
    st.warning("No ranked suppliers available for report generation.")
    st.stop()

# Executive Summary
st.markdown("### Executive Summary")
requirement = session.requirement

st.markdown(f"""
<div class="glass-card">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom: 12px;">
        <span style="color:#94a3b8; font-size:0.85rem;">Session Generated: {session.created_at.strftime('%B %d, %Y %H:%M UTC') if session.created_at else 'N/A'}</span>
    </div>
    <p style="font-size:1.05rem; margin-bottom:1rem;"><strong style="color:white;">Requirement Prompt:</strong> "{requirement.raw_query if requirement else 'N/A'}"</p>
    <div style="display:grid; grid-template-columns: repeat(3, 1fr); gap:16px;">
        <div><span style="color:#94a3b8; font-size:0.85rem;">Evaluated Candidates</span><br><strong style="font-size:1.2rem; color:white;">{len(session.suppliers)}</strong></div>
        <div><span style="color:#94a3b8; font-size:0.85rem;">Unique Entities</span><br><strong style="font-size:1.2rem; color:white;">{len(ranked)}</strong></div>
        <div><span style="color:#94a3b8; font-size:0.85rem;">Micro-Query Cost</span><br><strong style="font-size:1.2rem; color:#38bdf8;">${session.budget.total_spent:.3f} USD</strong></div>
    </div>
</div>
""", unsafe_allow_html=True)

# Primary Recommendation
st.markdown("### Primary Supplier Recommendation")
top_supplier, _ = ranked[0]

web_url = top_supplier.website or (top_supplier.source_urls[0] if top_supplier.source_urls else None)
site_domain = urlparse(web_url).netloc if web_url else "Web Directory"

best_price = None
best_moq = None
if top_supplier.products:
    prices = [p.normalized_unit_price for p in top_supplier.products if p.normalized_unit_price]
    moqs = [p.moq for p in top_supplier.products if p.moq]
    best_price = min(prices) if prices else None
    best_moq = min(moqs) if moqs else None

st.markdown(f"""
<div class="glass-card" style="background: linear-gradient(135deg, rgba(56,189,248,0.12), rgba(129,140,248,0.08)); border: 1px solid rgba(56,189,248,0.3);">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;">
        <h3 style="margin:0; font-size:1.4rem;">{top_supplier.name}</h3>
        <span style="background:#0284c7; color:white; padding:4px 12px; border-radius:20px; font-weight:700; font-size:0.85rem;">Top Candidate</span>
    </div>
    <div style="margin-bottom: 12px;">
        {f'<a href="{web_url}" target="_blank" style="color:#38bdf8; text-decoration:none; font-weight:600;">🌐 {web_url}</a>' if web_url else f'<span style="color:#94a3b8;">🌐 {site_domain}</span>'}
    </div>
    <div style="display:flex; gap:2rem; flex-wrap:wrap;">
        {f'<div><span style="color:#94a3b8; font-size:0.85rem;">Unit Price</span><br><strong style="font-size:1.4rem; color:white;">₹{best_price:.1f}/pc</strong></div>' if best_price is not None else ''}
        {f'<div><span style="color:#94a3b8; font-size:0.85rem;">MOQ</span><br><strong style="font-size:1.4rem; color:white;">{best_moq:,} pcs</strong></div>' if best_moq is not None else ''}
    </div>
</div>
""", unsafe_allow_html=True)

if len(ranked) > 1:
    st.markdown("### Candidate Alternatives")
    for i, (supplier, _) in enumerate(ranked[1:], start=2):
        price = None
        moq = None
        if supplier.products:
            prices = [p.normalized_unit_price for p in supplier.products if p.normalized_unit_price]
            moqs = [p.moq for p in supplier.products if p.moq]
            price = min(prices) if prices else None
            moq = min(moqs) if moqs else None

        alt_url = supplier.website or (supplier.source_urls[0] if supplier.source_urls else None)
        alt_domain = urlparse(alt_url).netloc if alt_url else "Web Directory"

        st.markdown(f"""
        <div class="glass-card" style="padding: 1rem 1.2rem; margin-bottom: 0.8rem;">
            <div style="display:flex; justify-content:space-between; align-items:center;">
                <h4 style="margin:0;">#{i} {supplier.name}</h4>
                <div>
                    {f'<a href="{alt_url}" target="_blank" style="color:#38bdf8; text-decoration:none; font-size:0.85rem;">🌐 {alt_domain}</a>' if alt_url else f'<span style="color:#94a3b8; font-size:0.85rem;">🌐 {alt_domain}</span>'}
                </div>
            </div>
            {(f'<div style="margin-top:6px; font-size:0.9rem; color:#cbd5e1;">Unit Price: <strong>₹' + f'{price:.1f}/pc</strong></div>') if price is not None else ''}
            {(f'<div style="margin-top:4px; font-size:0.9rem; color:#cbd5e1;">MOQ: <strong>' + f'{moq:,} pcs</strong></div>') if moq is not None else ''}
        </div>
        """, unsafe_allow_html=True)

st.markdown("---")

report_text = f"""# ProcureX Autonomous Procurement Recommendation Report
Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

## Requirement Prompt
{requirement.raw_query if requirement else 'N/A'}

## Primary Recommendation
{top_supplier.name}
Website: {web_url or 'N/A'}
{f'- Unit Price: ₹{best_price:.1f}/pc' if best_price is not None else ''}
{f'- Minimum Order Quantity: {best_moq:,} pcs' if best_moq is not None else ''}

## Alternatives
"""
for i, (s, _) in enumerate(ranked[1:], start=2):
    s_link = s.website or (s.source_urls[0] if s.source_urls else 'N/A')
    report_text += f"\n#{i} {s.name} — Link: {s_link}"

report_text += f"""

## Research Audit Summary
- Micro-Query Cost Spent: ${session.budget.total_spent:.3f} USD

---
Generated by ProcureX Autonomous B2B Procurement Intelligence Agent — An APEX Creation
"""

# Download Buttons (PDF and Markdown)
col_dl1, col_dl2 = st.columns(2)

with col_dl1:
    pdf_bytes = generate_pdf_report(
        requirement.raw_query if requirement else 'N/A',
        top_supplier,
        ranked[1:],
        session.budget.total_spent
    )
    st.download_button(
        label="Download Recommendation Report (PDF)",
        data=pdf_bytes,
        file_name=f"procurex_report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M')}.pdf",
        mime="application/pdf",
        use_container_width=True
    )

with col_dl2:
    st.download_button(
        label="Download Recommendation Report (Markdown)",
        data=report_text,
        file_name=f"procurex_report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M')}.md",
        mime="text/markdown",
        use_container_width=True
    )
